### ISSUE TITLE
Input Box and Enter instead of each key being sent immediatly

### ISSUE THREAD

**Issue by CaptainAngle** [commandblockguy/terminal-ce#10]
Whenever I press a key, it automatically sends it to the serial. I would like there to be a way to have a prompt like on most serial monitors.
![Screenshot 2024-07-20 154959](https://github.com/user-attachments/assets/8002fae3-c6e9-46c3-aeaa-5c45612b86b1)
(The input box at the bottom)

**Comment by commandz0** [comment]
This is a terminal emulator, not a serial monitor.
I suppose I could add a backend that performs line buffering, but it would probably be better to just make a separate program for that, since a terminal emulator and a serial monitor are two very different things even though they both allow a user to interact with a serial connection.
